class LanguageFile {
  static String selectedLanguage = "english";

  static Map<String, String> spanish = {
    "create account": "CREAR UNA CUENTA",
    "sign in": "INICIAR SESIÓN",
    "welcome to givers health": "Bienvenido a Givers Health",
    "find": "Encuentre recursos, orientación experta y apoyo comunitario a lo largo de su trayectoria como cuidador.",
    "welcome": "¡Bienvenido de nuevo!",
    "Your Email": "Tu correo electrónico",
    "Your Password": "Tu contraseña",
    "BACK": "atrás",
    "Please enter email": "Por favor ingrese su correo electrónico",
    "Please enter password": "Por favor, ingrese contraseña",
    "Help us, help you.": "Ayúdanos, te ayudamos.",
    "Fill out a short assessment about where you are in your caregiving journey. This assessment helps us to create better recommendations and match you with others.":
        "Complete una breve evaluación sobre dónde se encuentra en su viaje como cuidador. Esta evaluación nos ayuda a crear mejores recomendaciones y a emparejarlo con otros.",
    "START NOW": "INICIAR EVALUACIÓN",
    "I'LL DO THIS LATER": "LO HARÉ MÁS TARDE",
    "Let’s get some information about the person you care for.": "Obtengamos algo de información sobre la persona que cuida.",
    "You will need:": "Necesitará:",
    "Medicaid and Medicare Status": "Estado de Medicaid y Medicare",
    "Diagnoses": "Diagnósticos",
    "Your Zip Code": "Su código postal",
    "Your Loved One’s Zip Code": "El código postal de su ser querido",
    "What if I don’t have these?": "¿Qué pasa si no los tengo?",
    "Start": "COMIENZO",
    "Your Loved One’s Zip Code": "El código postal de su ser querido",
    "Does your loved one have Medicaid?": "¿Su ser querido tiene Medicaid?",
    "Select one(1) option": "Seleccione una (1) opción",
    "Yes": "sí",
    "No": "No",
    "I don’t know": "No sé",
    "Next": "Próxima",
    "Does your loved one have Medicare or Medicare Advantage?": "¿Su ser querido tiene Medicare o Medicare Advantage?",
    "Select one(1) option": "Seleccione una (1) opción",
    "Yes, Medicare": "Si, Medicare",
    "Yes, Medicare Advantage": "Sí, Medicare Advantage",
    "No": "No",
    "I don’t know": "No sé",
    "BACK": "atrás",
    "Next": "Próxima",
    "Does your loved one have Medicare or Medicare Advantage?": "¿Su ser querido tiene Medicare o Medicare Advantage?",
    "Select one(1) option": "Seleccione una (1) opción",
    "Yes, Medicare": "Si, Medicare",
    "Yes, Medicare Advantage": "Sí, Medicare Advantage",
    "Is your loved one a Veteran or Spouse of a Veteran?": "¿Es su ser querido un veterano o el cónyuge de un veterano?",
    "Does your loved one have Long-Term Care Insurance or Life Insurance that includes Long-Term benefits?":
        "¿Tiene su ser querido un seguro de cuidado a largo plazo o un seguro de vida que incluya beneficios a largo plazo?",
    "Is your loved one diagnosed with any of the following?":
        "¿Se le ha diagnosticado a su ser querido alguno de los siguientes?",
    "Select as many options as you like": "Selecciona tantas opciones como quieras",
    "Diabetes": "Diabetes",
    "Heart Disease": "Enfermedad del corazón",
    "COPD": "EPOC",
    "Cancer": "Cáncer",
    "Stroke": "Carrera",
    "Kidney Disease": "Enfermedad del riñon",
    "Dementia or Alzheimer's": "Demencia o Alzheimer",
    "Mild cognitive impairment": "Defecto cognitivo leve",
    "Depression": "Depresión",
    "Hospital admission within the last year": "Ingresos hospitalarios en el último año",
    "Other serious physical health condition": "Otra condición de salud física grave",
    "Other serious mental health condition": "Otra condición de salud mental grave",
    "What is your relationship with your loved one?": "¿Cuál es su relación con su ser querido?",
    "Select as many options as you like": "Selecciona tantas opciones como quieras",
    "I am their spouse": "Soy su esposa",
    "I am their adult child": "Soy su hija adulta",
    "I am another relative": "Soy otra pariente",
    "I am a neighbor or friend": "Soy vecina o amiga",
    "I am their former spouse": "Soy su ex esposa",
    "Other": "Otra",
    "Success!": "¡Éxito!",
    "Thanks for telling us more about you and your loved one.": "Gracias por contarnos más sobre usted y su ser querido.",
    "Go to Home": "Ir a homescreen",
    "START ASSESSMENT": "INICIAR EVALUACIÓN",
    "I'LL DO THIS LATER": "LO HARÉ MÁS TARDE"
  };
  static Map<String, String> english = {
    "create account": "CREATE ACCOUNT",
    "sign in": "SIGN IN",
    "welcome to givers health": "Welcome to Givers Health",
    "find": "Find resources, expert guidance, and community support through your caregiving journey.",
    "welcome": "Welcome back!",
    "Your Email": "Your Email",
    "Your Password": "Your Password",
    "Back": "Back",
    "Please enter email": "Please enter email",
    "Please enter password": "Please enter password",
    "Help us, help you.": "Help us, help you.",
    "Fill out a short assessment about where you are in your caregiving journey. This assessment helps us to create better recommendations and match you with others.":
        "Fill out a short assessment about where you are in your caregiving journey. This assessment helps us to create better recommendations and match you with others.",
    "START NOW": "START NOW",
    "I’ll Do This Later": "I’ll Do This Later",
    "Let’s get some information about the person you care for.": "Let’s get some information about the person you care for.",
    "You will need:": "You will need:",
    "Medicaid and Medicare Status": "Medicaid and Medicare Status",
    "Diagnoses": "Diagnoses",
    "Your Zip Code": "Your Zip Code",
    "What if I don’t have these?": "What if I don’t have these?",
    "Start": "Start",
    "Your Loved One’s Zip Code": "Your Loved One’s Zip Code",
    "Does your loved one have Medicaid??": "Does your loved one have Medicaid??",
    "Select one(1) option": "Select one(1) option",
    "Yes": "Yes",
    "No": "No",
    "I don’t know": "I don’t know",
    "Next": "Next",
    "Does your loved one have Medicare or Medicare Advantage?": "Does your loved one have Medicare or Medicare Advantage?",
    "Select one(1) option": "Select one(1) option",
    "Yes, Medicare": "Yes, Medicare",
    "Yes, Medicare Advantage": "Yes, Medicare Advantage",
    "No": "No",
    "I don’t know": "I don’t know",
    "BACK": "BACK",
    "Next": "Next",
    "Does your loved one have Medicare or Medicare Advantage?": "Does your loved one have Medicare or Medicare Advantage?",
    "Select one(1) option": "Select one(1) option",
    "Yes, Medicare": "Yes, Medicare",
    "Yes, Medicare Advantage": "Yes, Medicare Advantage",
    "Is your loved one a Veteran or Spouse of a Veteran?": "Is your loved one a Veteran or Spouse of a Veteran?",
    "Does your loved one have Long-Term Care Insurance or Life Insurance that includes Long-Term benefits?":
        "Does your loved one have Long-Term Care Insurance or Life Insurance that includes Long-Term benefits?",
    "Is your loved one diagnosed with any of the following?": "Is your loved one diagnosed with any of the following?",
    "Select as many options as you like": "Select as many options as you like",
    "Diabetes": "Diabetes",
    "Heart Disease": "Heart Disease",
    "COPD": "COPD",
    "Cancer": "Cancer",
    "Stroke": "Stroke",
    "Kidney Disease": "Kidney Disease",
    "Dementia or Alzheimer's": "Dementia or Alzheimer's",
    "Mild cognitive impairment": "Mild cognitive impairment",
    "Depression": "Depression",
    "Hospital admission within the last year": "Hospital admission within the last year",
    "Other serious physical health condition": "Other serious physical health condition",
    "Other serious mental health condition": "Other serious mental health condition",
    "What is your relationship with your loved one?": "What is your relationship with your loved one?",
    "Select as many options as you like": "Select as many options as you like",
    "I am their spouse": "I am their spouse",
    "I am their adult child": "I am their adult child",
    "I am another relative": "I am another relative",
    "I am a neighbor or friend": "I am a neighbor or friend",
    "I am their former spouse": "I am their former spouse",
    "Other": "Other",
    "Success!": "Success!",
    "Thanks for telling us more about you and your loved one.": "Thanks for telling us more about you and your loved one.",
    "Go to Home": "Go to Home",
    "START ASSESSMENT": "START ASSESSMENT",
    "I'LL DO THIS LATER": "I'LL DO THIS LATER"
  };

  static Map<String, String> function1() {
    late Map<String, String> map1;
    if (selectedLanguage == "spanish") {
      map1 = spanish;
    } else if (selectedLanguage == "english") {
      map1 = english;
    } else {
      map1 = english;
    }
    return map1;
  }
}
